# Generated by Django 5.2 on 2025-08-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel_layers_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_msg',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='voice_messages/'),
        ),
    ]
