# Generated by Django 5.2 on 2025-08-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel_layers_app', '0002_chat_msg_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='profiles/nonprofile.png', upload_to='profiles/'),
        ),
    ]
